name: build-deploy

# Only run this when the main branch changes
on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:
  release:

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'euroargodev/ghpages_doc_template'
    defaults:
      run:
        shell: bash -l {0}
        
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3

      # Install dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Build the book
      - name: Build the book
        run: |
          jupyter-book build .

      # Zip the site (so it can be handed to the preview action)
#      - name: Zip the site
#        run: |
#          set -x
#          set -e
#          if [ -f site.zip ]; then
#              rm -rf site.zip
#          fi
#          zip -r site.zip ./_build/html
#      - uses: actions/upload-artifact@v3
#        with:
#          name: site-zip
#          path: ./site.zip

      # Upload the book's HTML as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "_build/html"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.repository == 'euroargodev/ghpages_doc_template'

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

#      # Push the site's HTML to github-pages (only if on main, previews are sent to netlify)
#      - name: Deploy to GitHub pages
#        uses: peaceiris/actions-gh-pages@v3.8.0
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./_build/html
#          enable_jekyll: false

      # Deploy the book's HTML to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


